name: dotnet core - build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generates the build version
      id: version
      run: echo "::set-output name=version::$(date +'%Y.%m.%d'.$GITHUB_RUN_NUMBER)"
    
    - name: Print Version Steps
      run: echo ${{steps.version.output.version}}

    - name: Print Version Env
      run: echo $version
      
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Build
      run: dotnet build --configuration Release
    - name: Unit Tests
      run: dotnet test
      
    - name: Build NuGet Package
      run: dotnet pack ./HttpWebRequestExecutor/HttpWebRequestExecutor.csproj --configuration Release -o NuGetPackages
      
    - name: Deploy NuGet Package
      run: dotnet nuget push ./NuGetPackages/HttpWebRequestExecutor.1.1.5.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
